server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://159.54.152.194:3306/forest_access?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "eO&AFfc9g-PAWGlGU"
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_updates: true
        order_inserts: true
    show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
